{% set name = "FireWorks" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f145c42929f2fb36487834685a3d887deeb1075ba1b39d248de08d0535d1947

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - pip
    - ruamel.yaml >=0.15.35
    - pymongo >=3.3.0
    - Jinja2 >=2.8.0
    - six >=1.10.0
    - monty >=1.0.1
    - python-dateutil >=2.5.3
    - tabulate >=0.7.5
    - flask >=0.11.1
    - flask-paginate >=0.4.5
    - gunicorn >=19.6.0
    - tqdm >=4.8.4
    - paramiko >=2.4.2
    - pathlib2
    - requests >=2.01
    - fabric >=2.3.1
    - matplotlib-base >=2.0.1
    - python-igraph >=0.7.1
    - importlib-metadata

test:
  imports:
    - fireworks
  commands:
    - pip check

about:
  home: https://materialsproject.github.io/fireworks
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: The Fireworks Workflow Management Repo.

  description: |
    FireWorks stores, executes, and manages calculation workflows.
  doc_url: https://materialsproject.github.io/fireworks/
  dev_url: https://github.com/materialsproject/fireworks

extra:
  recipe-maintainers:
    - jan-janssen
