travis:
  secure:
    BINSTAR_TOKEN: O7A5PjSFEK4/Bj5bxtxqrIPnlqgIJuaRuQ/vpC0tLrjatSCBK+lW6AlXPDJH5YuxesyNbxAtyjuFXUya77CExIiNj2KnOfa8p33C/+8N7EU4yBftVGa8mgUzGSIwXCecErdtYEwEbvZEy5BVBT2bmUfmAGhjcUe/j1N2yK3950r9Ac7a/YMCmCJTBDoASh6sZ/tlJ919pEWZ3BdQxire9n08QOhHv8s8h1iYQPG9i+etuDyuKozAXCLY916uREpD1NQ5vuYb7Lsu8OwQQib7wuY1IHPDPuyxb92+FH0R0DrfGmnxru7RqEsqN4IElf9xrU7R8EmEdeLtdScSExb5/n2J7AtrmRczHyk/kOH42QSUWHL7UYHHn25r4dnChxsF2yvicxTQSJSr09eht8ZiKs+Tw8cXOkUqwkEtIZBG8Unf1nJEVarQ6N5Qrpv8Irf+4/ln91QgObgAhEN8MQfUUeWcgGkrTKS+y53HWhsyGVVNscGi5rXXkCKjNSU1O3mOd8ZD6BzmdV0hGbXtCCWykwX3IBaNl+dVBd4fs7fAHRVgbvP69C6PS3/QXRlQ0SBNPpkhnmzJAg2M9YytlYlZjHYmCImk5JVvUhbpVMeRkZpz6XMIm+CVrs+uLPIIoLNi1Zm33JUeyuPRiX45WSA1U6R96wY5z9MioOPJN78pdyk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
